name: Build cnping

on:
  push:
  pull_request:

jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
           debhelper-compat \
           libglvnd-dev \
           libx11-dev \
           libxext-dev \
           libxinerama-dev \
           mesa-common-dev
           # Would be nice if we could pull those directly from debian/control
           # Do we need to version-lock debhelper-compat?
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential \
          binutils-mingw-w64-i686 \
          gcc-mingw-w64-i686 \
          g++-mingw-w64-i686 \
          devscripts \
          appstream \
          desktop-file-utils

    - name: Build
      run: make cnping cnping.exe
        
    - uses: actions/upload-artifact@v3
      with:
        name: cnping-exe
        path: "*.exe"
        
    - name: Build deb
      run: debuild --no-sign
      
    - uses: actions/upload-artifact@v3
      with:
        name: cnping-exe
        path: /**/*.deb
          
    - name: Validate AppStream data
      run: appstreamcli validate freedesktop/com.github.cntools.cnping.metainfo.xml
    - name: Validate desktop file
      run: desktop-file-validate freedesktop/com.github.cntools.cnping.desktop
      
#  Build-RPM-for-Fedora:
#    runs-on: ubuntu-latest
#    container: dreua/ ...
#    steps:
#    - name: RPM Build
#      run: /cnping/cnping-build
#    - uses: actions/upload-artifact@v3
#      with:
#        name: cnping-fedora-rpm
#        path: /github/home/rpmbuild/**/*.rpm
