name: Build cnping

on:
  push:
  pull_request:

jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
           debhelper-compat \
           libglvnd-dev \
           libx11-dev \
           libxext-dev \
           libxinerama-dev \
           mesa-common-dev
           # Would be nice if we could pull those directly from debian/control
    - name: Install more dependencies
      run: |
        sudo apt-get install -y \
          make \
          build-essential \
          binutils-mingw-w64-i686 \
          gcc-mingw-w64-i686 \
          g++-mingw-w64-i686 \
          devscripts \
          appstream \
          desktop-file-utils

    - name: Build
      run: make cnping cnping.exe
        
    - uses: actions/upload-artifact@v3
      with:
        name: cnping-exe
        path: "*.exe"
        
    - name: Build deb
      run: debuild --no-sign
      
    - uses: actions/upload-artifact@v3
      with:
        name: cnping-debian
        path: |
          /home/runner/work/cnping/*.deb
          /home/runner/work/cnping/*.ddeb
          
    - name: Validate AppStream data
      run: appstreamcli validate freedesktop/com.github.cntools.cnping.metainfo.xml
    - name: Validate desktop file
      run: desktop-file-validate freedesktop/com.github.cntools.cnping.desktop
      
  Build-RPM-for-Fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
    # No checkout needed
    - name: Install dependencies
      run: |
        sudo dnf install -y \
            rpm-build rpmdevtools \
            gcc \
            make \
            libXinerama-devel \
            libXext-devel \
            libX11-devel \
            libappstream-glib \
            desktop-file-utils 
    - name: Prepare build environment
      run: |
        curl -o cnping.spec -L https://raw.githubusercontent.com/dreua/cnping-rpmspec/nightly/cnping.spec
        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - name: Download source as described in spec
      run: spectool --get-files --sourcedir cnping.spec
    - name: Build RPM
      run: rpmbuild -ba cnping.spec
    - uses: actions/upload-artifact@v3
      with:
        name: cnping-fedora-rpm
        path: /github/home/rpmbuild/**/*.rpm
